-- 코드를 입력하세요

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * S.SALES) AS SALES
FROM AUTHOR A, BOOK B, BOOK_SALES S
WHERE A.AUTHOR_ID = B.AUTHOR_ID
    AND B.BOOK_ID = S.BOOK_ID
    AND S.SALES_DATE BETWEEN TO_DATE('2022-01-01', 'YYYY-MM-DD') AND TO_DATE('2022-01-31', 'YYYY-MM-DD')
GROUP BY B.CATEGORY, A.AUTHOR_ID, A.AUTHOR_NAME
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC;