-- 코드를 입력하세요
SELECT  P.PRODUCT_CODE, (SUM(O.SALES_AMOUNT) * P.PRICE) AS SALES
FROM PRODUCT P, OFFLINE_SALE O
WHERE O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_CODE, P.PRICE
ORDER BY SALES DESC, P.PRODUCT_CODE;