-- 코드를 입력하세요
WITH CAR AS (SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE C.CAR_ID = H.CAR_ID
        AND (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV')
    GROUP BY C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE
    HAVING MAX(H.END_DATE) < TO_DATE('2022-11-01', 'YYYY-MM-DD')
            )

SELECT C.CAR_ID, C.CAR_TYPE, TO_NUMBER((100 - P.DISCOUNT_RATE) * C.DAILY_FEE * 30 / 100 ) AS FEE
FROM CAR C, CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
WHERE C.CAR_TYPE = P.CAR_TYPE
    AND P.DURATION_TYPE = '30일 이상'
    AND (100 - P.DISCOUNT_RATE)  * C.DAILY_FEE * 30 / 100 >= 500000 
    AND (100 - P.DISCOUNT_RATE) * C.DAILY_FEE * 30 / 100 < 2000000
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;