-- 코드를 입력하세요
WITH FOOD AS (SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
             FROM FOOD_ORDER
             WHERE  TO_CHAR(PRODUCE_DATE, 'YYYYMM') = '202205'
             GROUP BY PRODUCT_ID
             )
            
SELECT F.PRODUCT_ID, P.PRODUCT_NAME, F.AMOUNT * P.PRICE AS TOTAL_SALES
FROM FOOD F INNER JOIN FOOD_PRODUCT P ON F.PRODUCT_ID = P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC,P.PRODUCT_ID