-- 코드를 입력하세요
WITH ORDERSUM AS (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
                 FROM JULY
                 GROUP BY FLAVOR
                 )


SELECT F.FLAVOR 
FROM FIRST_HALF F 
    LEFT OUTER JOIN ORDERSUM O 
    ON O.FLAVOR = F.FLAVOR
ORDER BY (F.TOTAL_ORDER + O.TOTAL_ORDER) DESC
FETCH FIRST 3 ROWS ONLY;
