-- 코드를 입력하세요
WITH RANK AS (SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY COUNT(*) DESC)

SELECT MP.MEMBER_NAME, R.REVIEW_TEXT, TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE 
FROM REST_REVIEW R LEFT OUTER JOIN MEMBER_PROFILE MP ON R.MEMBER_ID = MP.MEMBER_ID
WHERE MP.MEMBER_ID IN (SELECT MEMBER_ID FROM RANK WHERE ROWNUM = 1)
ORDER BY REVIEW_DATE, R.REVIEW_TEXT;